source 'http://rubygems.org'

gem 'activerecord', '6.1.7.1', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sinatra'
gem 'nokogiri'
gem 'sqlite3', '~>1.3.6'
gem 'require_all'
gem 'rake'
gem 'tux'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tod', git: 'https://github.com/jackc/tod'
